# version: '3.2'

# services:
#   frontend:
#     build: ./react-frontend
#     ports:
#       - "3000:3000"
#     networks:
#       - my_network 

#   backend:
#     build: ./springboot-backend
#     ports:
#       - "9090:8080"
#     depends_on:
#       - database
#     links: 
#       - database 
#     networks:
#       - my_network   

#   database:
#     image: mysql:latest
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: akshay11
#       MYSQL_DATABASE: employee-database
#       MYSQL_USER: akshay
#       MYSQL_PASSWORD: akshay#11
#     ports:
#       - "3306:3306"
#     networks:
#       - my_network 
      
# networks:
#   my_network:


version: '3.2'

services:
  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"

  backend:
    build: ./springboot-backend
    ports:
      - "9090:8080"
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akshay11
      MYSQL_DATABASE: employee-database
      MYSQL_USER: akshay
      MYSQL_PASSWORD: akshay#11
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
