name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy with Docker Compose
      run: |
        docker-compose up -d

    - name: Test
      run: |
        # Add your testing commands here

    # - name: Clean up
    #   run: |
    #     docker-compose down
