apiVersion: apps/v1
kind: Deployment
metadata:
  name: backened
  namespace: three-tier
  labels:
    role: backend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      # imagePullSecrets:
      # - name: ecr-registry-secret
      containers:
      - name: backend
        image: public.ecr.aws/l1u7n5d4/employee-backend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend.amanpathakdevops.study/api/tasks"
        ports:
        - containerPort: 8080
